-- =======================
-- What is Execution Plan
-- =======================
-- Roadmap generated by a data base on how it will execute query step by step
-- How to check execution, beside execute we have 3 options
-- 1] Display estimated execution plan 
-- 2] Include Actual Execution plan 
-- 3] Include live query statistics

SELECT
	*
FROM FactResellersSales_HP
ORDER BY SalesOrderNumber